codecov:
  notify:
    after_n_builds: 4
comment:
  after_n_builds: 4
coverage:
  status:
    project:
      default:
        target: 94%
    patch:
      default:
        target: 90%
fixes:
  - "_build/default/lib/concuerror/::"
