sudo: false

language: erlang

script:
- curl -#fSLo ./rebar3 https://s3.amazonaws.com/rebar3/rebar3 && chmod +x ./rebar3
- export PATH="$PATH:$PWD"
- rebar3 version
- $TEST

# Two stages, so that basic tests are run first
stages:
- basic
- test

matrix:
# fast_finish: true

  # The Travis job that checks latest OTP version is allowed to fail
  # (see relevant include below)
  allow_failures:
  - env: TEST='.travis/travis_has_latest_otp_version'

  include:

  # When otp_release is unspecified, the first value in the corresponding
  # list below will be used

  # Check that the latest Erlang version is tested

  # This test will fail with 'X' when a new version is available via kerl.
  # At that point, update THIS test's otp_release to the new one.
  # The test will keep failing with '!', until Travis has the new version.
  # When the test starts failing with 'X' again, Travis has the new version.
  # At that point, update otp_release in the corresponding list below

  - env: TEST='.travis/travis_has_latest_otp_version'
    otp_release: 20.3
    stage: basic

  # Check dialyzer
  - env: TEST='rebar3 dialyzer'
    stage: basic

  # Code coverage test, that includes tests and tests-real
  - env: TEST='make cover'
    stage: test

  # Minimal support for R16B03-1
  - env: TEST='make tests-real'
    otp_release: R16B03-1
    stage: test

env:
  global:
  - CONCUERROR_COVER="$PWD/cover/data"
  matrix:
  - TEST='make tests-real'
  - TEST='make tests'

otp_release:

  # Two latest minor versions of the most recent OTP release
  # Remember to also update the badge in README.md

  - 20.3
  - 20.2

  # Last minor version of older OTP releases

  - 19.3
  - 18.3
  - 17.4
  # R16B03-1 is minimally supported (see matrix section)


after_failure: './.travis/after_failure'

before_script:
- cp plts/plt-$TRAVIS_OTP_RELEASE .concuerror_plt || true
before_cache:
- mkdir -p plts
- cp .concuerror_plt plts/plt-$TRAVIS_OTP_RELEASE || true
cache:
   directories:
   - plts

before_install:
  - .travis/before_install

after_success:
  - .travis/after_success
