sudo: false

language: erlang

script: "make $TEST"

stages:
  - basic
  - test

matrix:
  fast_finish: true
  include:
  - stage: basic
    env: TEST=travis_has_latest_otp_version
  - env: TEST=dialyze
  - stage: test
    env: TEST=cover
  - otp_release: R16B03-1
    env: TEST=tests-real
  exclude:
  - otp_release: 20.1

env:
  - TEST=tests-real
  - TEST=tests

otp_release:
  - 20.1
  - 20.0
  - 19.3
  - 18.3
  - 17.4

after_failure: "./.travis/after_failure"

before_script: "./.travis/recover_plt"
before_cache: "./.travis/store_plt"
cache:
   directories:
   - plts
