os: linux

dist: xenial

language: erlang

branches:
  only:
  - master
  - /^\d+\..*/ # version tags

stages:
  - basic
  - test
  - website

jobs:
  fast_finish: true

  # Jobs that are allowed to fail:
  allow_failures:
  - env: TEST=".travis/travis_has_latest_otp_version"

  include:

  # When otp_release is unspecified, the first value in the corresponding
  # list further down in this file will be used

  # Check that the latest Erlang version is tested
  # See the warning printed by the script to understand why this test
  # has a separate otp_release specification.
  - env: TEST=".travis/travis_has_latest_otp_version"
    otp_release: 23.1
    stage: basic

  # FLAG is used by Codecov reporter (.travis/after_success)
  - env: TEST="make tests-unit" FLAG="unit_tests"
    stage: basic

env:

  # FLAG is used by Codecov reporter (.travis/after_success)
  - TEST=".travis/run make tests-1" FLAG="tests-1"
  - TEST=".travis/run make tests-2" FLAG="tests-2"
  - TEST=".travis/run make tests-real" FLAG="tests_real"

otp_release:

  # Two latest minor versions of the most recent OTP release.

  # When a new major OTP release is enabled, also update the badge in
  # README.md and the argument given to generate_version_hrl in
  # rebar.config

  - 23.0

  # Last minor version of older OTP releases

  - 22.3
  - 21.3
  - 20.3


# Travis build steps configuration

addons:
  apt:
    packages:
    - moreutils

cache:
  timeout: 30
  directories:
  - "$HOME/.cache/rebar3"
  - "$HOME/.rvm/"

before_script:
  - .travis/before_script

script:
 - $TEST

after_success:
  - .travis/after_success

after_failure:
  - .travis/after_failure
