title:            Concuerror
description:      Concuerror is a model checking tool for testing and verifying concurrent Erlang programs.
logo:             site-logo.png
disqus_shortname: 
#Comment out url when working locally to resolve base urls correctly
url:             http://concuerror.com
author: Vahnatai

# Owner/author information
owner:
  name:           Stavros Aronis
  avatar:         http://www.gravatar.com/avatar/5730e85681def67cb10151437519f39d?s=200
  email:          aronisstav@gmail.com
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/111091514508576496337?rel=author

# Analytics and webmaster tools stuff goes here
google_analytics: UA-43607387-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
links:
  - title: <i class="fas fa-home"></i> Home
    url: /
  - title: <i class="fas fa-newspaper"></i> News
    url: /news
  - title: <i class="fas fa-download"></i> Download
    url: /download
  - title: <i class="fas fa-question-circle"></i> FAQ
    url: /faq
  - title: <i class="fas fa-info-circle"></i> Tutorials
    url: /tutorials
  - title: <i class="fas fa-book"></i> Publications    
    url: /publications
  - title: <i class="fas fa-envelope"></i> Contact
    url: /contact
  - title: <i class="fas fa-rss"></i> Feed
    url: /feed.xml
  - title: <i class="fab fa-github"></i> Github
    url: https://github.com/parapluu/Concuerror

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Stockholm
future:      false
highlighter: rouge
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title:output_ext

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

syntax_highlighter_opts:
  tab_width: 4
  bold_every: 10
  css: class

plugins:
  - jekyll-gist
  - jekyll-seo-tag

include: [".htaccess"]
exclude: ["CNAME", "Gemfile", "post.thor", "README.md", "Makefile"]
