name: Basic

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest
    container: erlang:latest
    strategy:
      matrix:
        target:
          - lint
          - dialyzer
    name: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '~/.cache'
          key: ${{ runner.os }}-rebar-${{ matrix.target }}-${{ hashFiles(format('{0}{1}', github.workspace, '/rebar.config')) }}
          restore-keys: |
            ${{ runner.os }}-rebar-${{ matrix.target }}-
            ${{ runner.os }}-rebar-
      - run: make ${{ matrix.target }}
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
          working-directory: doc
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 23
          elixir-version: master
      - run: make -C doc test
