name: Tests

on:
  push:
    branches: master
  pull_request:
    branches: master

env:
  THREADS: 2

jobs:
  basic:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - lint
          - dialyzer
    container: erlang:latest
    name: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '~/.cache'
          key: ${{ runner.os }}-rebar-${{ matrix.target }}-${{ hashFiles(format('{0}{1}', github.workspace, '/rebar.config')) }}
          restore-keys: |
            ${{ runner.os }}-rebar-${{ matrix.target }}-
            ${{ runner.os }}-rebar-
      - run: make ${{ matrix.target }}
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
          working-directory: doc
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 23
          elixir-version: master
      - run: make -C doc test
  tests-unit:
    runs-on: ubuntu-latest
    container: erlang:23.0
    steps:
      - uses: actions/checkout@v2
      - run: make tests-unit
      - run: rebar3 covertool generate
      - uses: codecov/codecov-action@v1
        with:
          file: _build/test/covertool/concuerror.covertool.xml
          flags: tests-unit
  tests-latest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp:
          # When a new major OTP release is enabled, also update the badge in
          # README.md and the argument given to generate_version_hrl in
          # rebar.config
          - '23.0'
        target:
          - tests-1
          - tests-2
          - tests-real
    container: erlang:${{ matrix.otp }}
    name: OTP ${{ matrix.otp }} - ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v2
      - run: .github/scripts/covertool_setup
      - run: make ${{ matrix.target }}
        env:
          CONCUERROR: ${{ github.workspace }}/priv/concuerror
          CONCUERROR_COVER: ${{ github.workspace}}/cover/data
      - run: .github/scripts/covertool_combine
      - uses: codecov/codecov-action@v1
        with:
          file: cover/coverage.xml
          flags: ${{ matrix.target }}
  tests-older:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Two latest minor versions of the most recent OTP release.
        # Last minor version of older OTP releases
        otp:
          - 22
          - 21
          - 20
        target:
          - tests-1
          - tests-2
          - tests-real
    container: erlang:${{ matrix.otp }}
    name: OTP ${{ matrix.otp }} - ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v2
      - run: make ${{ matrix.target }}
