name: Website

on:
  push:
    branches: master
    paths: 'docs/**'
  pull_request:
    branches: master
    paths: 'docs/**'
  schedule:
    # Run at 00:00 UTC on the first day of each month
    - cron: '00 00 1 * *'

jobs:
  test:
    strategy:
      matrix:
        target:
          - test
          - test-external
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true
          working-directory: docs
      - run: make -C docs ${{ matrix.target }}
